services:
  express:
    image: node:20
    container_name: equipment_express
    restart: unless-stopped
    networks:
      - equipment_network
    volumes:
      - ../../API/:/app/
      - ./.env:/app/.env
    working_dir: /app
    command: npm run start

networks:
  equipment_network:
    external: true
