version: '3'

services:
  express:
    restart: always
    container_name: equipment_express
    image: node:20
    volumes:
      - ../../API/:/app/
      - ./.env:/app/.env
    working_dir: /app
    command: npm run start
    ports:
      - "8082:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
