services:
  mongo:
    image: mongo:7-jammy
    container_name: equipment_mongo
    restart: unless-stopped
    env_file:
      - ./mongo/.env
    volumes:
      - mongo_data_volume:/data/db:rw
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo_network
  express:
    depends_on:
      - mongo
    image: node:22-alpine
    container_name: equipment_express
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        npm install --no-save &&
        npm run start
      "
    volumes:
      - ./express/:/app/:ro
      - express_node_modules_volume:/app/node_modules:rw
    networks:
      - express_network
      - mongo_network
  angular:
    image: node:22-alpine
    container_name: equipment_angular
    working_dir: /app
    command: >
      sh -c "
        npm install --no-save &&
        npm run build
      "
    volumes:
      - ./angular:/app:ro
      - angular_node_modules_volume:/app/node_modules:rw
      - angular_dist_volume:/app/dist:rw
      - angular_browser_volume:/app/dist/browser:rw

volumes:
  mongo_data_volume:
    name: equipment_mongo_data_volume
  express_node_modules_volume:
    name: equipment_express_node_modules_volume
  angular_node_modules_volume:
    name: equipment_angular_node_modules_volume
  angular_dist_volume:
    name: equipment_angular_dist_volume
  angular_browser_volume:
    name: equipment_angular_browser_volume

networks:
  mongo_network:
    driver: bridge
    name: equipment_mongo_network
  express_network:
    driver: bridge
    name: equipment_express_network
