services:
  angular:
    image: node:20
    container_name: equipment_angular
    volumes:
      - ../../site/:/app/
      - ./environment.ts:/app/src/environments/environment.ts
      - volume:/app/dist/browser
    working_dir: /app
    command: npm run build

volumes:
  volume:
    name: equipment_angular_data
